### PR TITLE
Add Docker build

### PR DESCRIPTION
**Pull request by pfxuan**
This PR reuses the existing ubuntu CI build logic to build local or remote docker images across different setup.

### CODE REVIEW

**Comment by pierotofy** [comment]
Nice!! Love the fact that there's variables to control the lib/ubuntu version. Thanks for the PR @pfxuan !

**Comment by pfxuan** [comment]
@pierotofy Thank you for your help and support. Looking forward to see the next move for ODM + OpenSplat.

**Comment by parkerlreed** [comment]
I tried the ROCm dockerfile through `podman` and while seemingly creating the image successfully after setting up all the deps, it doesn't seem to compile the final binary. 

The README doesn't really say anything after running the setup of how to run through Docker. 

Is there anything special for that?

**Comment by pierotofy** [comment]
I think the Dockerfile.rocm file is missing the build commands (everything else should be there though).

https://github.com/pierotofy/OpenSplat/blob/main/Dockerfile#L46

vs. 

https://github.com/pierotofy/OpenSplat/blob/main/Dockerfile.rocm#L70

@pfxuan might have more insights.

**Comment by pfxuan** [comment]
Good catch. Dockerfile.rocm includes the full version of ROCm/HIP build environment but is missing the actual compile and build part. It should be very similar to this step. I'll probably add it from the next PR with an extra ROCm 6.0.2 support:    
- https://github.com/pierotofy/OpenSplat/blob/main/.github/workflows/hip.yml#L163

**Pull request merged**
